# Generated by Django 5.1.2 on 2026-04-01 06:34

import client_tickets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_ticket_types(apps, schema_editor):
    ClientTicketType = apps.get_model("client_tickets", "ClientTicketType")
    Department = apps.get_model("task_app", "Department")
    default_names = [
        "PM Dashboard",
        "Campaign Management",
        "Bug Fixing - Live",
        "Bug Fixing - Staging",
        "Issues",
        "New Engineering Requirement",
        "Publishing",
        "Research",
        "Sales",
        "Service",
        "Testing",
        "Others",
    ]
    for name in default_names:
        department = Department.objects.filter(name__iexact=name).first()
        ClientTicketType.objects.get_or_create(
            name=name,
            defaults={
                "department": department,
                "is_active": True,
            },
        )


def remove_default_ticket_types(apps, schema_editor):
    ClientTicketType = apps.get_model("client_tickets", "ClientTicketType")
    ClientTicketType.objects.filter(
        name__in=[
            "PM Dashboard",
            "Campaign Management",
            "Bug Fixing - Live",
            "Bug Fixing - Staging",
            "Issues",
            "New Engineering Requirement",
            "Publishing",
            "Research",
            "Sales",
            "Service",
            "Testing",
            "Others",
        ]
    ).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_app', '0003_task_viewers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'email'],
                'constraints': [models.UniqueConstraint(fields=('email', 'phone_number'), name='unique_client_contact_email_phone')],
            },
        ),
        migrations.CreateModel(
            name='ClientTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_app.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ticket_type_other', models.CharField(blank=True, max_length=255)),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_email', models.EmailField(max_length=254)),
                ('requester_number', models.CharField(max_length=30)),
                ('user_type', models.CharField(choices=[('internal', 'Internal'), ('client', 'Client'), ('agency', 'Agency'), ('vendor', 'Vendor')], default='internal', max_length=20)),
                ('source_system', models.CharField(choices=[('manual', 'Manual'), ('pm_dashboard', 'PM Dashboard'), ('campaign_management', 'Campaign Management'), ('api', 'API'), ('inditech_ticketing', 'Inditech Ticketing')], default='manual', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(blank=True, choices=[('', '---------'), ('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_for_client', 'Waiting For Client'), ('waiting_for_inditech', 'Waiting For Inditech'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('auto_closed', 'Auto Closed'), ('cancelled', 'Cancelled')], default='', max_length=32)),
                ('inditech_status', models.CharField(blank=True, choices=[('', '---------'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('needs_clarification', 'Needs Clarification'), ('completed', 'Completed'), ('closed', 'Closed')], default='', max_length=32)),
                ('client_status', models.CharField(blank=True, choices=[('', '---------'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('needs_clarification', 'Needs Clarification'), ('completed', 'Completed'), ('closed', 'Closed')], default='', max_length=32)),
                ('last_inditech_action_at', models.DateTimeField(blank=True, null=True)),
                ('last_client_action_at', models.DateTimeField(blank=True, null=True)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('inditech_completed_at', models.DateTimeField(blank=True, null=True)),
                ('client_completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_tickets_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_app.department')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_tickets_managed', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='client_tickets.clientcontact')),
                ('ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_tickets.clienttickettype')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientTicketUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('inditech', 'Inditech'), ('client', 'Client'), ('system', 'System')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('', '---------'), ('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_for_client', 'Waiting For Client'), ('waiting_for_inditech', 'Waiting For Inditech'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('auto_closed', 'Auto Closed'), ('cancelled', 'Cancelled')], default='', max_length=32)),
                ('inditech_status', models.CharField(blank=True, choices=[('', '---------'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('needs_clarification', 'Needs Clarification'), ('completed', 'Completed'), ('closed', 'Closed')], default='', max_length=32)),
                ('client_status', models.CharField(blank=True, choices=[('', '---------'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('needs_clarification', 'Needs Clarification'), ('completed', 'Completed'), ('closed', 'Closed')], default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_updates', to='client_tickets.clientcontact')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='client_tickets.clientticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_ticket_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=client_tickets.models.client_ticket_upload_to)),
                ('uploaded_by_role', models.CharField(choices=[('client', 'Client'), ('pm', 'Project Manager'), ('inditech', 'Inditech')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='client_tickets.clientticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_ticket_attachments', to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='client_tickets.clientticketupdate')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.RunPython(seed_default_ticket_types, remove_default_ticket_types),
    ]
