# Generated by Django 5.1.2 on 2026-04-07 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_tickets', '0001_initial'),
        ('task_app', '0004_taskattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientticket',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='clientticket',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference', ''), _negated=True), fields=('source_system', 'external_reference'), name='unique_client_ticket_source_external_reference'),
        ),
    ]
